#ifndef OPEN_FWD_CONF_H
#define OPEN_FWD_CONF_H

#define REPORT_TOT_POWER

#define UART2_ENABLED

#define MOT1_ENABLED
#define MOT2_ENABLED
#define REPORT_MOT_CURRENT
#define REPORT_MOT_PROTECT

#define RUD1_ENABLED
#define RUD2_ENABLED
#define RUD3_ENABLED
#define RUD4_ENABLED
#define RUD5_ENABLED
#define RUD6_ENABLED
#define REPORT_RUD_PROTECT

#define LED1_TICK_ENABLE
#define LED2_TICK_ENABLE
#define LED3_TICK_ENABLE
#define LED4_TICK_ENABLE
#endif
