#ifndef COMMUNICATE_H
#define COMMUNICATE_H

#define MSG_LEN 16

#define ROTOR_PREFIX 0xF0
#define MOTOR_CURRENT 0x00 // MOT_ID(starts from 1) CURR_LSB CURR_MSB
#define TOTAL_POWER 0x01 // CURR_LSB CURR_MSB VOLT_LSB VOLT_MSB
#define MOTOR_PROTECT 0x02 // MOT_ID
#define MOTOR_ANGLE 0x03 // MOT_ID ANGLE_LSB ANGLE_MSB
#define RUDDER_PROTECT 0x04 // RUD_ID(starts from 1)
#define MOTOR_SET_MODE 0x05 // MOT_ID CTRL_MODE
#define MOTOR_SET_TRG 0x06 // MOT_ID TRG_LSB TRG_MSB
#define RUDDER_SET_TRG 0x07 // RUD_ID TRG_VAL(range 0-199)
#define LED_SET_PWM 0x08 // LED_ID(starts from 1) PWM_VAL
#define LED_SET_TICK 0x09 // LED_ID TICK_SLOT TICK_LSB TICK_MSB
#define LED_RESET_TICK 0x0A // LED_ID
#define BEEP_SET 0x0B // BEEP_EN FRAC_LSB FRAC_MSB

#endif